export const GET_LISTS = "GET_LISTS"
export const GET_CUR_BOARD = "GET_CUR_BOARD"

export const SEND_BOARD_START = "SEND_BOARD_START"
export const SEND_BOARD_SUCCESS = "SEND_BOARD_SUCCESS"
export const SEND_BOARD_FAIL = "SEND_BOARD_FAIL"

export const FETCH_BOARDS_START = "FETCH_BOARDS_START"
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS"
export const FETCH_BOARDS_FAIL = "FETCH_BOARDS_FAIL"

export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const CHECK_AUTH_STATUS = "CHECK_AUTH_STATUS"

export const NEEDS_REDIRECT = "NEEDS_REDIRECT"
export const INITIALIZE_REDIRECT = "INITIALIZE_REDIRECT"
